version: '3.8'

services:

  # Node.js 应用服务
  node_app:
    image: node:v1.0 # 指定要使用的镜像,本地没有镜像会从远程仓库拉取              
    container_name: compose_node # 指定容器的名称       
    ports: # 将主机端口映射到容器端口
      - "678:88"                      
    volumes:  # 挂载主机目录到容器目录
      - ./node:/app/ 
    environment: # 设置环境变量
      ROOT_NAME: "hyx" 
    build: # 有 build 字段:根据 Dockerfile 构建新镜像;没有 build 字段:使用 image 字段指定的镜像
      context: ./node  # 使用node目录作为构建上下文
      dockerfile: Dockerfile # 指定 Dockerfile 路径,相对于context路径

  # 其他服务

# 定义卷
volumes:
  mysql_data: # 定义名为 mysql_data 的卷
