
# 该镜像是基于nginx:latest镜像构建的
FROM mysql:latest

# 构建docker镜像
# docker build  -t mysql:v1.0 .
# 基于镜像启动一个docker容器
# docker run -d --name mysql_container -e MYSQL_ROOT_PASSWORD=111111 -p 2002:3306 -v C:\Users\HuangWeiSheng\Desktop\my-vue3\notes\docker\mysql\DataBase:/var/lib/mysql mysql:v1.0
